version: "3"

services:
  server:
    container_name: app_server
    build: ./server
    ports:
      - 8080:8080
    environment:
      FCM_SERVER_URL: "https://fcm.googleapis.com/fcm/send"
      FCM_SERVER_KEY: "{FCM_SERVER_KEY}"

  web:
    container_name: web_server
    build: ./web
    ports:
      - 80:80

